require('config.colour')
require('config.behaviour')
require('config.statusline')
require('config.ui')
require('config.keys')
require('config.lsp')

require('plugins.smart-splits')
require('plugins.leap')
require('plugins.treesitter')
require('plugins.mini-surround')

require('utils.autopairs')
require('utils.format')
require('utils.todo_highlight')
